name: Lab Bicep Deployment

on: 
  workflow_dispatch:
    inputs:
      labPath:
        description: 'Lab nr (Directory where the bicepfile for the lab is located)'
        required: true
        default: 'lab3'

env:
  RESOURCE_GROUP: ${{ vars.RG_NAME }}${{ github.event.inputs.labPath }}
  LOCATION: ${{ vars.LOCATION }} # Default location for resources

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Log in to Azure
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # Step 3: Ensure the Resource Group exists (create if it doesn't exist)
    - name: Create Resource Group for ${{ github.event.inputs.labPath }}
      run: |
        az group create --name ${{ env.RESOURCE_GROUP }} --location ${{ env.LOCATION }} \
        --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} --tags Project=scalingCloudLab

    - name: Deploy Bicep file for ${{ github.event.inputs.labPath }}
      run: |
        az deployment group create \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} \
          --template-file ${{ github.event.inputs.labPath }}/lab.bicep \
          --parameters applicationImage=${{ vars.ACR_IMAGE }} \
          --mode Incremental